name: aws-function-ci

on: [push]

jobs:
  lambda-function:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install zip
      uses: montudor/action-zip@v1
    - name: create zip file
      run: zip -r code.zip .
    - name: aws cli v2
      uses: imehedi/actions-awscli-v2@latest
      with:
        args: "lambda update-function-code --function-name arn:aws:lambda:ap-south-1:010438487838:function:testcicd --zip-file fileb://code.zip"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: "ap-south-1"
